name: Live Endpoint Test

on:
  schedule:
    - cron: "00 * * * *" # Run every hour (on the hour)
  workflow_dispatch:

jobs:
  live-endpoint:
    name: Live Endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Display Rust Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version

      - name: Live Endpoint Test
        env:
          LIVE_ENDPOINT_URL: ${{ secrets.LIVE_ENDPOINT_URL }}
          LIVE_ENDPOINT_TOKEN: ${{ secrets.LIVE_ENDPOINT_TOKEN }}
        run: |
          cargo test --verbose --features serde_debugging --test live_endpoint_canary
